// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCab3ikUrkk8kWypN6mlBBDRVHvTlxtT8g',
    appId: '1:1035985414483:web:10112c1aeafdfa31d319a6',
    messagingSenderId: '1035985414483',
    projectId: 'ui-task-miniproject',
    authDomain: 'ui-task-miniproject.firebaseapp.com',
    storageBucket: 'ui-task-miniproject.firebasestorage.app',
    measurementId: 'G-ZXEGGNZ18B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SyJYERCVZvomuRsgH9-MhuLbmj73jAA',
    appId: '1:1035985414483:android:28c4165f52fc09a5d319a6',
    messagingSenderId: '1035985414483',
    projectId: 'ui-task-miniproject',
    storageBucket: 'ui-task-miniproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYDE8VFDVvgnGzNOaxvQlMuCqdoJgrbTs',
    appId: '1:1035985414483:ios:9364590ccddb8ecbd319a6',
    messagingSenderId: '1035985414483',
    projectId: 'ui-task-miniproject',
    storageBucket: 'ui-task-miniproject.firebasestorage.app',
    iosBundleId: 'com.example.uiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYDE8VFDVvgnGzNOaxvQlMuCqdoJgrbTs',
    appId: '1:1035985414483:ios:9364590ccddb8ecbd319a6',
    messagingSenderId: '1035985414483',
    projectId: 'ui-task-miniproject',
    storageBucket: 'ui-task-miniproject.firebasestorage.app',
    iosBundleId: 'com.example.uiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCab3ikUrkk8kWypN6mlBBDRVHvTlxtT8g',
    appId: '1:1035985414483:web:4ae0882653c24a2ad319a6',
    messagingSenderId: '1035985414483',
    projectId: 'ui-task-miniproject',
    authDomain: 'ui-task-miniproject.firebaseapp.com',
    storageBucket: 'ui-task-miniproject.firebasestorage.app',
    measurementId: 'G-Q8EKVFRCVF',
  );
}
